kind: Deployment
apiVersion: apps/v1
metadata:
  name: helidon-movie-api-mp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: helidon-movie-api-mp
  template:
    metadata:
      labels:
        app: helidon-movie-api-mp
    spec:
      containers:
        - name: helidon-movie-api-mp
          image: icn.ocir.io/cnbkloa0ci62/movie/helidon-movie-api-mp:8be5787b64a9ac04103a9cfc06135f2149da0715
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
      imagePullSecrets:
        - name: ocirsecret
